services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./thingsboard/mosquitto/config:/mosquitto/config
      - ./thingsboard/mosquitto/certs:/mosquitto/certs
      - ./thingsboard/mosquitto/data:/mosquitto/data
      - ./thingsboard/mosquitto/log:/mosquitto/log
    restart: unless-stopped
